### ISSUE TITLE
Add possibility for wildcard character for source tag

### ISSUE THREAD

**Issue by Slohrsh** [ethlo/zally-maven-plugin#2]
It would be great if I could configure the source like that: <source>src/main/resources/api/*.yml</source>

**Comment by ethlo** [comment]
Hi! Thanks for your request. I will have a look at it.

**Comment by ethlo** [comment]
I had a look at this, but I find it hard to understand how it should work, as the OpenAPI definitions may consist of many files. How to determine what are the "main" files?
